#!/bin/sh
# Fold ext/* crates into the base server (§3.3). Runs inside the image build.
# Convention: ext/<name>/ is a crate named <name> exposing
# `pub fn router() -> axum::Router`; it gets nested at /x/<name>.
set -eu

cd "$(dirname "$0")"
REG=server/src/ext_registry.rs
TOML=server/Cargo.toml

exts=""
for d in ext/*/; do
    [ -f "${d}Cargo.toml" ] || continue
    exts="$exts $(basename "$d")"
done

# Reset marker section.
awk '/# ext-deps-begin/{print; skip=1; next} /# ext-deps-end/{skip=0} !skip' "$TOML" > "$TOML.tmp"
mv "$TOML.tmp" "$TOML"

if [ -z "$exts" ]; then
    cat > "$REG" <<'EOF'
// Extension registry — REGENERATED by build-ext.sh at image build when ext/
// crates exist (§3.3). Each ext crate exposes `pub fn router() -> axum::Router`
// and is nested under /x/{crate-name}, inside the same token gate.
//
// Default: no extensions.

pub fn mount(r: axum::Router) -> axum::Router {
    r
}
EOF
    echo "build-ext: no extensions"
    exit 0
fi

{
    echo "// GENERATED by build-ext.sh — do not edit."
    echo
    echo "pub fn mount(r: axum::Router) -> axum::Router {"
    echo "    r"
    for e in $exts; do
        echo "        .nest(\"/x/$e\", $e::router())"
    done
    echo "}"
} > "$REG"

for e in $exts; do
    sed -i "/# ext-deps-begin/a $e = { path = \"../ext/$e\" }" "$TOML"
done

echo "build-ext: mounted:$exts"
